### ISSUE TITLE
Hi, I get and error in google chrome

### ISSUE THREAD

**Issue by uzi98f** [DeepDeepDeep/LoLEsportsWatcher#12]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

"manifest_version": 2,

I dont know if its normal:) thankyou

**Comment by DeepDeepDeep** [comment]
> Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
> 
> "manifest_version": 2,
> 
> I dont know if its normal:) thankyou

It is normal, I need to update it to V3, but I'm not sure how to go about it yet cause they changed how the background worker works.
