### ISSUE TITLE
Suggestion to have the option to open stream in youtube

### ISSUE THREAD

**Issue by vhfls** [DeepDeepDeep/LoLEsportsWatcher#14]
Hello! I've noticed that sometimes twitch can be unreliable such as the stream randomly dies or it doesn't play automatically. I'm wondering if there's an option for the extension to open YouTube streams instead of Twitch streams (assuming YouTube streams are available)?

**Comment by DeepDeepDeep** [comment]
Twitch should always play automatically, but the issue with Youtube is that it doesn't automatically play when you go to the direct link.

**Comment by DeepDeepDeep** [comment]
> Hello! I've noticed that sometimes twitch can be unreliable such as the stream randomly dies or it doesn't play automatically. I'm wondering if there's an option for the extension to open YouTube streams instead of Twitch streams (assuming YouTube streams are available)?

Twitch should always play automatically, but the issue with Youtube is that it doesn't automatically play when you go to the direct link.

I will see if there's anything I can do to detect if the stream dies.

**Comment by vhfls** [comment]
Thanks! Hoping the upcoming LPL stream doesn't die randomly again 😥
