### ISSUE TITLE
Im not sure it only happen to me or its general

### ISSUE THREAD

**Issue by uzi98f** [DeepDeepDeep/LoLEsportsWatcher#16]
I know, to win drops the stream must have "volume"  (if anyone knows if it can be muted and still win can clear me of doubts) and you can mute the tabs from google chrome. Im not sure if RIOT has made a change, but now if you open a stream the stream automatically mutes, and now you must manually increase the volume. 

Thankyou deepdeepdeep for your work

**Comment by uzi98f** [comment]
when you refresh de page, the stream from the page automatic mute the stream, and sometimes using the script, I get stream muteds

**Comment by DeepDeepDeep** [comment]
I'm pretty sure Riot/Twitch did that. I can't control the volume at all.

**Comment by uzi98f** [comment]
there its a shortcut that you can click the stream and then press M to unmute the volume:) maybe it can be a wait 

maybe doing automatic click in the stream and automatic press M

**Comment by DeepDeepDeep** [comment]
It's not something I want to implement anyway. I also don't think the sound part matters as the checkmark is still there even if it's muted. I've had streams muted before and I still received drops.

**Comment by uzi98f** [comment]
I read that now the stream must have volumen, it can be 1% porcent of volumen, But whell maybe its me, I cant win drops if the stream its muted, thanks anyway its a good script

**Comment by DeepDeepDeep** [comment]
> I read that now the stream must have volumen, it can be 1% porcent of volumen, But whell maybe its me, I cant win drops if the stream its muted, thanks anyway its a good script

I can confirm that you don't need to have volume for drops. if you aren't receiving drops, you are likely shadowbanned. Don't watch all the leagues, only watch the big ones or you will get shadowbanned for 7-14 days.
