### ISSUE TITLE
Possible to connect more than 1 acc somehow?

### ISSUE THREAD

**Issue by 22oo** [DeepDeepDeep/LoLEsportsWatcher#20]
hey, great app btw!
i noticed that if i leave it open in incognito and normal browser at the same time it only opens the normal windows, even if the extension is allowed in incognito & im logged in lolesports in both versions. 
so i was wondering if it's possible to connect more than 1 accounts somehow..
thanks alot, have a good day!

**Comment by DeepDeepDeep** [comment]
> hey, great app btw! i noticed that if i leave it open in incognito and normal browser at the same time it only opens the normal windows, even if the extension is allowed in incognito & im logged in lolesports in both versions. so i was wondering if it's possible to connect more than 1 accounts somehow.. thanks alot, have a good day!

Make a new Chrome profile and you can use another account. Keep both the windows with each profile open and then it will work.
