### ISSUE TITLE
automatic play dont work anymore, but I find a solution

### ISSUE THREAD

**Issue by uzi98f** [DeepDeepDeep/LoLEsportsWatcher#26]
when the tab its open and you decide youtube or twitch that doesnt matter, the stream doesnt play. But when the tab of the navegator is open and you go to "option " and yo chage the stream from twitch to youtube or youtube to twitch they automatic start playing the stream, maybe thaqt would be a great solution to autostart and play the stream

**Comment by DeepDeepDeep** [comment]
> when the tab its open and you decide youtube or twitch that doesnt matter, the stream doesnt play. But when the tab of the navegator is open and you go to "option " and yo chage the stream from twitch to youtube or youtube to twitch they automatic start playing the stream, maybe thaqt would be a great solution to autostart and play the stream

For auto play to work, you need to do this:
`--autoplay-policy=no-user-gesture-required` flag is required for Youtube streams to automatically play. It's recommended you have a separate chrome shortcut with this flag otherwise every site will autoplay automatically.

**Comment by uzi98f** [comment]
I think dont work anymore using the --autoplay-policy=no-user-gesture-required, stop and you need to click @DeepDeepDeep

**Comment by DeepDeepDeep** [comment]
> I think dont work anymore using the --autoplay-policy=no-user-gesture-required, stop and you need to click @DeepDeepDeep

It's been working for me on my linux machine. Likely user error on your side.

**Comment by uzi98f** [comment]
window, I dont get autoplay, I need to press to start
