### ISSUE TITLE
the auto play dont work or maybe Im doing wrong

### ISSUE THREAD

**Issue by uzi98f** [DeepDeepDeep/LoLEsportsWatcher#27]
--autoplay-policy=no-user-gesture-required

hi can you show please where I can add that? im using google chrome thankss

**Comment by DeepDeepDeep** [comment]
> --autoplay-policy=no-user-gesture-required
> 
> hi can you show please where I can add that? im using google chrome thankss




1. Create a Chrome Shortcut:
2. Right-click on your desktop or Start Menu and select New > Shortcut.
3. In the location field, browse to the Chrome executable (usually found at C:\Program Files\Google\Chrome\Application\chrome.exe) or type the path.
4. After the Chrome path, you can add flags. For example:
```
"C:\Program Files\Google\Chrome\Application\chrome.exe" --autoplay-policy=no-user-gesture-required
```
